#include "/Engine/Private/Common.ush"
#include "/Engine/Public/Platform.ush"


float4 SimpleColor;

void MainVS(
	in float4 InPosition : ATTRIBUTE0, 
	in float2 InUV : ATTRIBUTE1,
	out float2 OutUV : TEXCOORD0, 
	out float4 OutPosition : SV_Position)
{
	OutPosition = InPosition;
	OutUV = InUV;
}


void MainPS(in float2 UV : TEXCOORD0, out float4 OutColor : SV_Target0)
{
	OutColor = float4(UV, 1, 1);
	//OutColor = SimpleColor;
}

